Module 18 - Statistics, NumPy and Pandas


In [2]:
import numpy as np

# Check the version of the numpy package
print('numpy:', np.__version__)

# Checking the available methods
print(dir(np))

numpy: 2.2.1
['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_globals', '_int_extended_msg', '_mat', '_msg', '_pyinstaller_hooks_dir', '_pytesttester', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'array_repr', 

In [3]:
# Creating int numpy arrays
# Creating python List
python_list = [1, 2, 3, 4, 5]

# Checking data types
print('Type:', type(python_list))  # <class 'list'>
print(python_list)  # [1, 2, 3, 4, 5]

two_dimensional_list = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
print(two_dimensional_list)  # [[0, 1, 2], [3, 4, 5], [6, 7, 8]]

# Creating Numpy(Numerical Python) array from python list
numpy_array_from_list = np.array(python_list)
print(type(numpy_array_from_list))  # <class 'numpy.ndarray'>
print(numpy_array_from_list)  # array([1, 2, 3, 4, 5])

Type: <class 'list'>
[1, 2, 3, 4, 5]
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [4]:
# Creating float numpy arrays
# Python list
python_list = [1, 2, 3, 4, 5]

# Creating a numpy array from the python list with float data type
numpy_array_from_list2 = np.array(python_list, dtype=float)
print(numpy_array_from_list2)  # array([1., 2., 3., 4., 5.])

[1. 2. 3. 4. 5.]


In [5]:
# Creating boolean numpy arrays
# Creating a numpy array with boolean data type
numpy_bool_array = np.array([0, 1, -1, 0, 0], dtype=bool)
print(numpy_bool_array)  # array([False,  True,  True, False, False])

[False  True  True False False]


In [6]:
numpy_two_dimensional_list = np.array(two_dimensional_list)
print(type(numpy_two_dimensional_list))  # <class 'numpy.ndarray'>
print(numpy_two_dimensional_list)  # array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
print(numpy_two_dimensional_list)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
# We can always convert an array back to a python list using tolist().
np_to_list = numpy_array_from_list.tolist()
print(type(np_to_list))
print('one dimensional array:', np_to_list)
print('two dimensional array:', numpy_two_dimensional_list.tolist())

<class 'list'>
one dimensional array: [1, 2, 3, 4, 5]
two dimensional array: [[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [9]:
print(f"Type of one dimensional array: {type(np_to_list)}")
print(f"One dimensional array: {np_to_list}")
print(f"Type of two dimensional array: {type(two_dimensional_list)}")
print(f"Two dimensional array: {two_dimensional_list}")

Type of one dimensional array: <class 'list'>
One dimensional array: [1, 2, 3, 4, 5]
Type of two dimensional array: <class 'list'>
Two dimensional array: [[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [10]:
# Numpy array from tuple
# Creating tuple in Python
python_tuple = (1, 2, 3, 4, 5)
print(type(python_tuple))  # <class 'tuple'>
print('python_tuple: ', python_tuple)  # python_tuple:  (1, 2, 3, 4, 5)

numpy_array_from_tuple = np.array(python_tuple)
print(type(numpy_array_from_tuple))  # <class 'numpy.ndarray'>
print('numpy_array_from_tuple: ', numpy_array_from_tuple)  # numpy_array_from_tuple:  [1 2 3 4 5]

<class 'tuple'>
python_tuple:  (1, 2, 3, 4, 5)
<class 'numpy.ndarray'>
numpy_array_from_tuple:  [1 2 3 4 5]


In [11]:
nums = np.array([1, 2, 3, 4, 5])
print(nums)
print('shape of nums: ', nums.shape)
print(numpy_two_dimensional_list)
print('shape of numpy_two_dimensional_list: ', numpy_two_dimensional_list.shape)
three_by_four_array = np.array([[0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11]])
print(three_by_four_array)
print('shape of three_by_four_array: ', three_by_four_array.shape)

[1 2 3 4 5]
shape of nums:  (5,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
shape of numpy_two_dimensional_list:  (3, 3)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape of three_by_four_array:  (3, 4)


In [12]:
print(f"Shape of numpy_array_from_list: {numpy_array_from_list.shape}")
print(f"Shape of numpy_array_from_list2: {numpy_array_from_list2.shape}")
print(f"Shape of numpy_array_from_tuple: {numpy_array_from_tuple.shape}")
print(f"Shape of numpy_bool_array: {numpy_bool_array.shape}")
print(f"Shape of numpy_two_dimensional_list: {numpy_two_dimensional_list.shape}")
print(f"Shape of three_by_four_array: {three_by_four_array.shape}")

Shape of numpy_array_from_list: (5,)
Shape of numpy_array_from_list2: (5,)
Shape of numpy_array_from_tuple: (5,)
Shape of numpy_bool_array: (5,)
Shape of numpy_two_dimensional_list: (3, 3)
Shape of three_by_four_array: (3, 4)


In [13]:
int_lists = [-3, -2, -1, 0, 1, 2, 3]
int_array = np.array(int_lists)
float_array = np.array(int_lists, dtype=float)

print(int_array)
print(int_array.dtype)
print(float_array)
print(float_array.dtype)

[-3 -2 -1  0  1  2  3]
int64
[-3. -2. -1.  0.  1.  2.  3.]
float64


In [14]:
print(int_array)
print(int_array.dtype)

print(float_array)
print(float_array.dtype)

[-3 -2 -1  0  1  2  3]
int64
[-3. -2. -1.  0.  1.  2.  3.]
float64


Module 18 - Statistics, NumPy and Pandas
Pandas Exercises:
Read the hacker_news.csv file from data directory
Get the first five rows
Get the last five rows
Get the title column as pandas series
Count the number of rows and columns
Filter the titles which contain python
Filter the titles which contain JavaScript
Explore the data and make sense of it


In [ ]:
import pandas as pd

# Read the hacker_news.csv file from data directory
df = pd.read_csv('data/hacker_news.csv')

# Get the first five rows
first_five_rows = df.head()
print("First five rows:")
print(first_five_rows)

# Get the last five rows
last_five_rows = df.tail()
print("\nLast five rows:")
print(last_five_rows)

# Get the title column as pandas series
title_series = df['title']
print("\nTitle column as pandas series:")
print(title_series)

# Count the number of rows and columns
rows, columns = df.shape
print(f"\nNumber of rows: {rows}, Number of columns: {columns}")

# Filter the titles which contain python
python_titles = df[df['title'].str.contains('python', case=False, na=False)]
print("\nTitles containing 'python':")
print(python_titles)

# Filter the titles which contain JavaScript
javascript_titles = df[df['title'].str.contains('JavaScript', case=False, na=False)]
print("\nTitles containing 'JavaScript':")
print(javascript_titles)

# Explore the data and make sense of it
print("\nData exploration:")
print(df.describe())
print(df.info())